project/project/urls.py
from django.contrib import admin
from django.urls import path
from ecommerce import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home_view'),
    path('reg',views.RegisterView.as_view(),name='reg_view'),
    path('login',views.UserLogin.as_view(),name='login_view'),
    # path('userlog',views.Userhome.as_view(),name='userhome_view'),
    path('logout',views.UserLogout.as_view(),name='logout_view'),
    path('productdetail/<int:id>',views.ProductDetailView.as_view(),name='product_detail'),
    path('addtocart/<int:id>',views.AddtoCart.as_view(),name='addto_cart'),
    path('cartlist',views.CartUserList.as_view(),name='cart_list'),
    path('placeorder/<int:cart_id>',views.PlaceOrderView.as_view(),name='place_order'),
    path('cartdelete/<int:id>',views.CartDelete.as_view(),name='cart_delete'),





]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    category_name=models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)
    def __str__(self):
        return self.category_name
    
class Products(models.Model):
    product_name=models.CharField(max_length=100)
    price=models.PositiveIntegerField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='image',null=True)
    description=models.CharField(max_length=100)
    def __str__(self):
        return self.product_name
    
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)
    options=(
    ('in-cart','in-cart'),
    ('cancelled','cancelled'),
    ('order-placed','order-placed')
    )
    status=models.CharField(max_length=100,choices=options,default='in-cart')

class OrderPlaced(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    order_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField(max_length=200)
    email=models.EmailField(max_length=255)
    options=(
    ('cancelled','cancelled'),
    ('order-placed','order-placed'),
    ('dispatched','dispatched'),
    ('delivered','delivered')
    )
    status=models.CharField(max_length=100,choices=options,default='order-placed')

project/ecommerce/forms.py
from django import forms
from django.contrib.auth.models import User
from ecommerce.models import Cart,OrderPlaced


class RegisterForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password','email']
        widgets={
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Fisrt Name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'User Name'}),
            'password':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email@gmail.com'}),

        }

class LoginForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password']
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'User Name'}),
            'password':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}),
        }

class CartForm(forms.ModelForm):
    class Meta:
        model=Cart
        fields=['quantity']
        widgets={
            'quantity':forms.NumberInput(attrs={'class':'form-control'}),
        }
class OrderForm(forms.ModelForm):
    class Meta:
        model=OrderPlaced
        fields=['address','email']
        widgets={
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'})
        }
       

project/ecommerce/views.py
from django.shortcuts import render,redirect
from django.views import View
from ecommerce.forms import RegisterForm,LoginForm,CartForm,OrderForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from ecommerce.models import Products,Category,Cart,OrderPlaced
from django.core.mail import send_mail,settings




# Create your views here.

class Home(View):
    def get(self,request,*args,**kwargs):
        data=Products.objects.all()
        return render(request,'index.html',{'products':data})
    
class RegisterView(View):
    def get(self,request,*args,**kwargs):
        form=RegisterForm()
        return render(request,'register.html',{'form':form})
    def post(self,request,*args,**kwargs):
        form=RegisterForm(request.POST)
        if form.is_valid():
            User.objects.create_user(**form.cleaned_data)
            messages.success(request,'Registration Successfully')
            return redirect('log_view')
        else:
            messages.error(request,'Invalid')
            return redirect('reg_view')

        
class UserLogin(View):
    def get(self,request,*args,**kwargs):
        form=LoginForm()
        return render(request,'login.html',{'form':form})
    def post(self,request,*args,**kwargs):
        uname=request.POST['username']
        psw=request.POST['password']
        user=authenticate(username=uname,password=psw)
        if user:
            login(request,user)
            messages.success(request,'Loggin Successfully')
            return redirect('home_view')
        else:
            messages.error(request,'Invalid Credentials')
            return redirect('log_view')
# class Userhome(View):
#     def get(self,request,*args,**kwargs):
#         return render(request,'userhome.html')
class UserLogout(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        messages.success(request,'Logout Successfully')
        return redirect('home_view')

class ProductDetailView(View):
    def get(self,request,*args,**kwargs):
        pid=kwargs.get('id')
        product=Products.objects.get(id=pid)
        return render(request,'productdetails.html',{'product':product})
    

class AddtoCart(View):
    def get(self,request,*args,**kwargs):
        form=CartForm()
        pid=kwargs.get('id')
        product=Products.objects.get(id=pid)
        return render(request,'addtocart.html',{'form':form,'product':product})
    def post(self,request,*args,**kwargs):
        u=request.user
        pid=kwargs.get('id')
        q=request.POST.get('quantity')
        p=Products.objects.get(id=pid)
        Cart.objects.create(user=u,quantity=q,product=p)
        return redirect('home_view')
    
class CartUserList(View):
    def get(self,request,*args,**kwargs):
        data=Cart.objects.filter(user=request.user).exclude(status='order-placed')
        return render(request,'Cartlistview.html',{'carts':data})
    
class PlaceOrderView(View):
    def get(self,request,*args,**kwargs):
        form=OrderForm()
        return render(request,'placeorder.html',{'form':form})
    def post(self,request,*args,**kwargs):
        cart_id=kwargs.get('cart_id')
        cart=Cart.objects.get(id=cart_id)
        user=request.user
        address=request.POST['address']
        email=request.POST['email']
        OrderPlaced.objects.create(user=user,cart=cart,address=address,email=email)
        send_mail('confirmation','order-placrd Successfully',settings.EMAIL_HOST_USER,[email])
        cart.status='Order-placed'
        cart.save()
        return redirect('home_view')
class CartDelete(View):
    def get(self,request,*args,**kwargs):
        cart_id=kwargs.get('id')
        data=Cart.objects.get(id=cart_id)
        data.delete()
        return redirect('cart_list')

project/ecommerce/templates/Cartlistview.html
{% extends 'index.html' %}
{% block content %}

<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for cart in carts %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{cart.product.image.url}}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{cart.product.product_name}}</h5>
                            <!-- Product price-->
                            ₹{{cart.product.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'place_order' cart.id %}">Place Order</a></div>
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'cart_delete' cart.id %}">Cancel</a></div>

                    </div>
                </div>
            </div>
        {% endfor %}
    <div>
</div>

{% endblock %}

project/ecommerce/templates/addtocart.html
{% extends 'index.html' %}
{% block content %}

<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <div class="col-8">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="{{product.image.url}}" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{product.product_name}}</h5>
                    <!-- Product price-->
                    ₹{{product.price}}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'addto_cart' product.id %}">Add to Cart</a></div>
            </div>
        </div>
    </div>
    <div class="col-4">   
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Add">
        </form>
        </div>
</div>





{% endblock %}

project/ecommerce/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'reg_view' %}">Register</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'login_view' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'logout_view' %}">Logout</a></li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">All Products</a></li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-dark" type="submit" href="{% url 'cart_list' %}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">  
                            {% if request.user.cart_set.all.count > 0 %}
                                {{request.user.cart_set.all.count}}
                            {% else %}
                                0
                            {% endif %}</span>                      
                    </a>
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>
    <!-- Section-->
{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products%}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.image.url}}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.product_name}}</h5>
                                    <!-- Product price-->
                                    ₹{{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product_detail' product.id %}">View options</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            <div>
        </div>
    </section>
{% endblock %}
    <!-- {% if messages %}
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

    <div class="alert alert-success  alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-warning  alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %} -->
    <!-- Footer-->
<footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
</footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

project/ecommerce/templates/login.html
<!doctype html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body class="d-flex vh-100 vw-100 align-items-center justify-content-center ">

        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="Submit" value="Login">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-warning  alert-dismissible fade show" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                </div>

            {%  endif %}
    {% endfor %}
  {% endif %}
        </form>
        
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

project/ecommerce/templates/placeorder.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}
                <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>

    </div>
</div>
{% endblock %}

project/ecommerce/templates/productdetails.html
{% extends 'index.html' %}

{% block content %}

<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{product.image.url}}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{product.product_name}}</h5>
                            <!-- Product price-->
                            ₹{{product.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'addto_cart' product.id %}">Add to Cart</a></div>
                    </div>
                </div>
            </div>
    <div>
</div>

{% endblock %}

project/ecommerce/templates/register.html
<!doctype html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body class="d-flex align-items-center justify-content-center ">
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="Submit">
            {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-warning  alert-dismissible fade show" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                    </div>
    
                {%  endif %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    
                    <div class="alert alert-success  alert-dismissible fade show" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                    </div>
                {%  endif %}
        {% endfor %}
      {% endif %}
        </form>

       
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>